# Generated by Django 4.2.7 on 2023-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resumedata_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
