# Generated by Django 4.2.7 on 2023-12-03 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resumedata_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
