# Generated by Django 4.2.7 on 2023-12-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resumedata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='Description1',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Description2',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Description3',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Domain1',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Domain2',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Domain3',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Professional_Skill_1',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Professional_Skill_2',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Professional_Skill_3',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Professional_Skill_4',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Description1',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Description2',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Description3',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Name1',
            field=models.CharField(default='Default Project', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Name2',
            field=models.CharField(default='Default Project', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Name3',
            field=models.CharField(default='Default Project', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Technical_Skill_1',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Technical_Skill_2',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Technical_Skill_3',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Technical_Skill_4',
            field=models.CharField(default='Default Skill', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='edudes',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='edudes2',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='edudes3',
            field=models.TextField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='eduname1',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='eduname2',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='eduname3',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='enddate',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='enddate2',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='enddate3',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='facebook',
            field=models.URLField(default='facebook', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='github',
            field=models.URLField(default='github', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='languages1',
            field=models.CharField(default='Default language', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='languages2',
            field=models.CharField(default='Default language', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='languages3',
            field=models.CharField(default='Default language', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='languages4',
            field=models.CharField(default='Default language', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider1',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider2',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider3',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider4',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider5',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider6',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider7',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_slider8',
            field=models.IntegerField(default='50', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='startdate',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='startdate2',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='startdate3',
            field=models.IntegerField(default='2000', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='twitter',
            field=models.URLField(default='twitter', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='url1',
            field=models.URLField(default='url'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='url2',
            field=models.URLField(default='url'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='url3',
            field=models.URLField(default='url'),
        ),
    ]
