# Generated by Django 4.2.7 on 2023-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resumedata_description1_resumedata_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='enddate',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='enddate2',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='enddate3',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skill_slider8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='startdate',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='startdate2',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='startdate3',
            field=models.IntegerField(default=2000),
        ),
    ]
