# Generated by Django 4.2.7 on 2023-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_resumedata_enddate_alter_resumedata_enddate2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='file_upload',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='images/'),
        ),
    ]
