# Generated by Django 4.2.7 on 2023-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_languages1_resumedata_language1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
