# Generated by Django 4.2.7 on 2023-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_resumedata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider1',
            new_name='skill_fill1',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider2',
            new_name='skill_fill2',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider3',
            new_name='skill_fill3',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider4',
            new_name='skill_fill4',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider5',
            new_name='skill_fill5',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider6',
            new_name='skill_fill6',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider7',
            new_name='skill_fill7',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_slider8',
            new_name='skill_fill8',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='github',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='twitter',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Domain1',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Domain2',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Project_Domain3',
            field=models.CharField(default='Default Domain', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Uni1',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Uni2',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Uni3',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
