# Generated by Django 4.2.7 on 2023-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_skill_slider1_resumedata_skill_fill1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='skill_label1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_label8',
            field=models.IntegerField(default=0),
        ),
    ]
