# Generated by Django 4.2.7 on 2023-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_resumedata_skill_percent1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='skill_percent2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_percent3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='skill_percent4',
            field=models.IntegerField(default=0),
        ),
    ]
