# Generated by Django 4.2.7 on 2023-12-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_resumedata_skill_percent2_resumedata_skill_percent3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill1',
            new_name='skill_range1',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill2',
            new_name='skill_range2',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill3',
            new_name='skill_range3',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill4',
            new_name='skill_range4',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill5',
            new_name='skill_range5',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill6',
            new_name='skill_range6',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill7',
            new_name='skill_range8',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_fill8',
            new_name='skill_rangel7',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label1',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label2',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label3',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label4',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label5',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label6',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label7',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_label8',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_percent1',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_percent2',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_percent3',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skill_percent4',
        ),
    ]
