# Generated by Django 4.2.7 on 2023-12-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_skill_fill1_resumedata_skill_range1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedata',
            old_name='skill_rangel7',
            new_name='skill_range7',
        ),
    ]
